services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: "local"
      APP_DEBUG: "true"
      APP_KEY: ""
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DATABASE: "laravel"
      DB_USERNAME: "laravel"
      DB_PASSWORD: "secret"

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
